# **Aula 1 - 02/03**

## **NumPy**

In [42]:
import numpy as np

In [43]:
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [44]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
print (meuArray)

[0 1 2 3 4 5 6 7 8]


In [46]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [47]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [50]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [51]:
array3 = np.arange (0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
array4 = np.arange(12)

In [53]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [54]:
type(array4)

numpy.ndarray

In [55]:
array4.dtype

dtype('float64')

In [56]:
vetor1 = np.array ([0, 1, 2, 3, 4])
print (vetor1)

[0 1 2 3 4]


In [57]:
vetor1 [3]

3

In [58]:
vetor1 [0:2]

array([0, 1])

In [59]:
s = np.array(['Python', 'Profissional', 'Java', 'Água'])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [60]:
s = np.array(['Python', 1464321315, 'Profissional', 'Java', 'Água'])
s

array(['Python', '1464321315', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

In [61]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [62]:
vetor1[0] = 'Novo elemento'
vetor1

ValueError: ignored

In [ ]:
vetor1[0] = 45.6
vetor1